### ISSUE TITLE
colorpicker with 'alpha' => true needs admin stylesheet adjustment

### ISSUE THREAD

**Issue by stabilimenta** [CMB2/CMB2#1143] opened 2018-06-01 19:39 UTC
With a color picker with the alpha transparency option, the entire metabox ends up with an overlay of the color. This overlay has a position: absolute but the parent element `<button>` only has the default positioning, making the overlay jump out of flow and cover everything. The solution is to add this to the admin stylesheet: 
      .cmb-row button { position: relative; }
**Before fix:**
<img width="561" alt="screen shot 2018-06-01 at 3 30 25 pm" src="https://user-images.githubusercontent.com/10748861/40860038-de2fe998-65b1-11e8-9fd5-fb53f8dd48bb.png">
**After fix:**
<img width="550" alt="screen shot 2018-06-01 at 3 31 59 pm" src="https://user-images.githubusercontent.com/10748861/40860037-de20c490-65b1-11e8-98d7-eb0c45a2f06c.png">

**Comment by tw2113** [comment] 2018-06-01 19:44
Can you provide your used field type settings for this? I want to try recreating myself and see what's going on as well, while still trusting what you're seeing.

**Comment by stabilimenta** [comment] 2018-06-01 19:47
`function evcd_register_page_metaboxes() {
	global $theme_prefix;

	$extra_content_sections = new_cmb2_box( array(
		'id'            => $theme_prefix . 'page-sections',
		'title'         => esc_html__( 'Extra Content Sections', 'evcd_textdomain' ),
		'object_types'  => array( 'page', ), // Post type
		'show_on'      => array( 'key' => 'page-template', 'value' => 'page-full-width.php' ),
		'priority'     => 'high',
		'closed'       => false,
	) );

	$group_field_id = $extra_content_sections->add_field( array(
		'id'          => $theme_prefix . 'content-group',
		'type'        => 'group',
		// 'repeatable'  => false, // use false if you want non-repeatable group
		'options'     => array(
			'group_title'   => esc_html__( 'Content Section {#}', 'evcd_textdomain' ), // since version 1.1.4, {#} gets replaced by row number
			'add_button'    => esc_html__( 'Add Another Content Section', 'evcd_textdomain' ),
			'remove_button' => esc_html__( 'Remove Content Section', 'evcd_textdomain' ),
			'sortable'      => true, // beta
			// 'closed'     => true, // true to have the groups closed by default
		),
	) );

	// Id's for group's fields only need to be unique for the group. Prefix is not needed.

	$extra_content_sections->add_group_field( $group_field_id, array(
		'name'    => esc_html__( 'Content Heading', 'evcd_textdomain' ),
		'id'      => 'section-heading',
		'type'    => 'text',
		'before_row'   => '
			<div class="cmb2-tabs">
				<ul class="tabs-nav">
					<li class="current"><a href="#tab-content-1">Content</a></li>
					<li><a href="#tab-content-2">Styling + Options</a></li>
				</ul>
				<div class="tab-content tab-content-1 current">
					<div class="row">
		',
		'after_row'   => '
				</div>
		',
	) );

	$extra_content_sections->add_group_field( $group_field_id, array(
		'name'    => esc_html__( 'Content', 'evcd_textdomain' ),
		'id'      => 'section-content',
		'type'    => 'wysiwyg',
		'options' => array( 'textarea_rows' => 20, ),
		'before_row'   => '
			<div class="row">
		',
		'after_row'   => '
				</div>
		',
	) );

	$extra_content_sections->add_group_field( $group_field_id, array(
		'name' => esc_html__( 'Content CSS classes', 'evcd_textdomain' ),
		// 'desc' => esc_html__( 'Applies css class to inner content wrapper', 'evcd_textdomain' ),
		'id'   => 'content-classes',
		'type' => 'text',
		'desc'             => esc_html__( 'Class names: full, twothirds, half, third, quarter, dark, light, right, left, center, padded, two-cols, three-cols, four-cols', 'evcd_textdomain' ),
		'before_row'   => '
			<div class="row">
		',
		'after_row'    => '
					</div>
				</div>
		',
	) );

	$extra_content_sections->add_group_field( $group_field_id, array(
		'name' => esc_html__( 'Section ID', 'evcd_textdomain' ),
		// 'desc' => esc_html__( 'CSS ID for this section', 'evcd_textdomain' ),
		'id'   => 'section-ID',
		'type' => 'text_medium',
		'desc' => esc_html__( 'Used for menu linking. For example, if ID is "my-section" menu link is "#my-section".', 'evcd_textdomain' ),
		'row_classes'	=> 'half',
		'before_row'   => '
			<div class="tab-content tab-content-2">
				<div class="row">
		',
	) );

	$extra_content_sections->add_group_field( $group_field_id, array(
		'name' => esc_html__( 'Section Wrapper CSS classes', 'evcd_textdomain' ),
		// 'desc' => esc_html__( 'Applies css class to inner content wrapper', 'evcd_textdomain' ),
		'id'   => 'section-css-classes',
		'type' => 'text_medium',
		'desc'    => esc_html__( 'page-width class will make it same width as page.', 'evcd_textdomain' ),
		'row_classes'	=> 'half',
		'after_row'	=> '
				</div>
		',
	) );

	$extra_content_sections->add_group_field( $group_field_id, array(
		'name'    => esc_html__( 'Background Color', 'evcd_textdomain' ),
		'id'   => 'section-background-color',
		'type' => 'colorpicker',
		'options' => array(
			'alpha' => true, // Make this a rgba color picker.
		),
		'before_row'   => '<div class="row">',
		'after_row'   => '</div>',
	) );

	$extra_content_sections->add_group_field( $group_field_id, array(
		'name' => esc_html__( 'Background Image', 'evcd_textdomain' ),
		'id'   => 'section-image',
		'type' => 'file',
		'options' => array(
			'url' => false, // Hide the text input for the url
		),
		'before_row'   => '<div class="row">',
		'after_row'   => '</div>',
	) );

	$extra_content_sections->add_group_field( $group_field_id, array(
		'name'             => esc_html__( 'Parallax Background', 'evcd_textdomain' ),
		'desc'             => esc_html__( 'Does not work on mobiles.', 'evcd_textdomain' ),
		'id'               => 'section-parallax',
		'type'             => 'radio_inline',
		'default' => 'false',
		'options'          => array(
			'false' => esc_html__( 'Off', 'evcd_textdomain' ),
			'true'   => esc_html__( 'On', 'evcd_textdomain' ),
		),
		'before_row'   => '<div class="row">',
		'after_row'    => '
					</div>
				</div>
			</div>
		',
	) );

}
`

**Comment by tw2113** [comment] 2018-06-01 20:29
What version of CMB2 are you running for this site? I'm not managing to recreate for 2.4.2. I did reduce things down to just the colorpicker field for easier viewing.

https://cloudup.com/cJ5QwmhJ3w2

In the screenshot you can see that I have an alpha value set, and the `<button>` has an inline position:relative css property.

**Comment by stabilimenta** [comment] 2018-06-01 20:32
I am using 2.2.4.

**Comment by stabilimenta** [comment] 2018-06-01 20:35
I will update!

**Comment by tw2113** [comment] 2018-06-01 20:36
Lots of good stuff, from what I recall, in the newer versions, definitely worth upgrading. If we confirm the issue is resolved post-update, we'll close this.

**Comment by stabilimenta** [comment] 2018-06-01 20:41
Yes, I can confirm the update fixed it. Sorry I didn't think about that before posting. Thank you for your help.

**Comment by tw2113** [comment] 2018-06-01 20:42
Welcome, glad it was an easy fix, all things considered.

**Closed by tw2113** 2018-06-01 20:42 UTC
