### ISSUE TITLE
how create fields in my sidebar?

### ISSUE THREAD

**Issue by johndiego** [CMB2/CMB2#1069] opened 2017-12-05 14:51 UTC
<b>how i can create fields in my sidebar using CMB2?</b>

thanks

**Comment by tw2113** [comment] 2017-12-05 14:59
Assuming you mean the sidebar of the admin editor screen, you would want to check out https://github.com/CMB2/CMB2/wiki/Box-Properties#context

Closing the issue as a whole as it's not a bug/feature request, but you can still respond afterwards as necessary.

We also request that for general support requests, users post those questions over at https://wordpress.org/support/plugin/cmb2 and we'll get them answered there.

**Closed by tw2113** 2017-12-05 14:59 UTC
