### ISSUE TITLE
CMB2 fields are not visible on term edit page

### ISSUE THREAD

**Issue by Brain8torm** [CMB2/CMB2#1272] opened 2019-05-23 13:36 UTC
CMB2 fields for terms are visible on add term page, but not on edit term page. If you look at the page code, the html code generated by CMB2 for Metabox is available. It is also visible that the layout of Metabox Yoast SEO is broken. If you add in CSS for .cmb2-metabox overflow: hidden;, the CMB2 metabox will become visible.

Wordpress 5.2.1
Yoast SEO 11.2.1
![Screenshot](https://user-images.githubusercontent.com/571307/58257020-bfdd2700-7d78-11e9-9847-9aeb5c2465b7.png)

**Comment by tw2113** [comment] 2019-05-23 13:57
Can you provide your CMB2 config for this term field customization and also what version of CMB2 you're using or if you're using a GH copy, which branch you're on.

**Comment by Brain8torm** [comment] 2019-05-23 15:59
I use CMB2 v.2.6.0 from GH (develop branch).

```
function bs_post_prop_metabox() {
	$bs_prefix = 'bs_';

	$bs_cmb_terms = new_cmb2_box( array(
		'id'            => $bs_prefix.'cmb_terms_props',
		'title'         => esc_html__( 'Свойства термина', 'bs-abutilons' ),
		'object_types'  => array( 'term' ),
		'taxonomies'	=> bs_get_taxonomies(),
	) );
	$bs_cmb_terms->add_field( array(
		'name'       => esc_html__( 'Заголовок H1', 'bs-abutilons' ),
		'desc'       => esc_html__( 'SEO Заголовок H1', 'bs-abutilons' ),
		'id'         => $bs_prefix.'seo_h1',
		'type'       => 'text',
	) );
	$bs_cmb_terms->add_field( array(
	    'name'    => 'Изображение',
	    'desc'    => 'Загрузите изображение для категории/термина',
	    'id'      => $bs_prefix.'term_image',
	    'type'    => 'file',
	    // Optional:
	    'options' => array(
	        'url' => false,
	    ),
	    'text'    => array(
	        'add_upload_file_text' => 'Выбрать изображение'
	    ),

	    'query_args' => array(
			'type' => array(
				'image/gif',
				'image/jpeg',
				'image/png',
			),
	    ),
	    'preview_size' => 'thumbnail',
	) );
}
add_action( 'cmb2_admin_init', 'bs_post_prop_metabox' );
```

Both fields are invisible, and after i add overflow:hidden to css and metabox became visible, button for upload image not work.

**Comment by tw2113** [comment] 2019-05-23 16:12
Couple thoughts.

We recommend against using develop branch for prod sites. Simply because it's our "will be" release branch and is most likely the place to experience breaking, like what I'm seeing here.

That said, I know we recently had https://github.com/CMB2/CMB2/commit/7fc4d691a639d874b13ea3ac45ee96730b098f43 committed. I checked out the commit immediately before it and saw similar issues as your screenshot. However, if I go back to the latest commit, the issue is fixed.

So I would say at minimum fetch the latest activity on the develop branch, or more ideally, switch over to one of the tagged versions which correspond to the stable releases.

**Comment by Brain8torm** [comment] 2019-05-23 20:18
I updated the files from the develop branch and the problem was solved. Thanks

**Comment by tw2113** [comment] 2019-05-23 20:44
Awesome.

**Closed by tw2113** 2019-05-23 20:44 UTC
