### ISSUE TITLE
GET_POST_META DONT WORK WITH TAXONOMY??

### ISSUE THREAD

**Issue by johndiego** [CMB2/CMB2#1116] opened 2018-04-18 03:07 UTC
![deepinscreenshot_20180417235453](https://user-images.githubusercontent.com/18476845/38909390-d4956d16-429a-11e8-8f67-13a37b4dd00c.png)
![deepinscreenshot_20180417235725](https://user-images.githubusercontent.com/18476845/38909472-1dff7b54-429b-11e8-8e23-e137dc0ed1ee.png)
![deepinscreenshot_20180418000401](https://user-images.githubusercontent.com/18476845/38909688-15b570ba-429c-11e8-8e71-8e59037bf83b.png)
![deepinscreenshot_20180418000453](https://user-images.githubusercontent.com/18476845/38909704-261807b0-429c-11e8-8f6e-fe8e2e28d35e.png)
![deepinscreenshot_20180418000537](https://user-images.githubusercontent.com/18476845/38909730-415aebc8-429c-11e8-84ff-74ff9b9f6cd8.png)

# HOW SOLVED THIS????
dont show selected taxonomy!

**Comment by tw2113** [comment] 2018-04-18 03:32
The `taxonomy_*` field types are meant as replacements for the default taxonomy metaboxes, and set post terms, not post meta.

See the notes at the end of the lines: 

https://cloudup.com/czv7t_TP-Xo

from https://github.com/CMB2/CMB2/wiki/Field-Types

For a field type that uses taxonomy terms and DOES save as post meta, please see our example over at https://github.com/CMB2/CMB2/wiki/Tips-&-Tricks#a-dropdown-for-taxonomy-terms-which-does-not-set-the-term-on-the-post and adapt as necessary for your own needs.

Hope this helps and clears up some confusion. Feel free to ask further questions if needed, but I am closing as it's not a bug or an enhancement.

**Closed by tw2113** 2018-04-18 03:32 UTC
